# Generated by Django 4.2 on 2023-04-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newegg', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
